export const GET_ARTIST_DATA = "GET_ARTIST_DATA";
export const GET_ARTIST = "GET_ARTIST";
export const GET_SONGS = "GET_SONGS";
export const GET_PLAYER_SONG = "GET_PLAYER_SONG";
export const ADD_TO_FAVOURITES = "ADD_TO_FAVOURITES"
export const REMOVE_FROM_FAVOURITES = "REMOVE_FROM_FAVOURITES"